kind: Pod
apiVersion: v1beta1
id: mysql
desiredState:
  manifest:
    version: v1beta1
    id: mysql
    containers:
      - name: mysql
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            # Change this password!
            value: yourpassword
        cpu: 100
        ports:
          - containerPort: 3306
        volumeMounts:
            # This name must match the volumes.name below.
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
    volumes:
      - name: mysql-persistent-storage
        source:
          persistentDisk:
            # This disk must already exist.
            pdName: mysql-disk
            fsType: ext4
labels:
  name: mysql